name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.YC_TOKEN }}
        function_id: ${{ secrets.YC_LAMBDA_ID }}
        runtime: 'nodejs16'
        memory: '128'
        entrypoint: 'index.handler'
        environment: LOGIN=${{ secrets.LOGIN }},PASSWORD=${{ secrets.PASSWORD }},MOSENERGO_LOGIN=${{ secrets.MOSENERGO_LOGIN }},MOSENERGO_PASSWORD=${{MOSENERGO_PASSWORD}},MOSENERGO_ACCOUNT=${{MOSENERGO_ACCOUNT}},MOSENERGO_ID_KNG=${{MOSENERGO_ID_KNG}},MOSENERGO_NM_ABN=${{MOSENERGO_NM_ABN}},BOT_TOKEN=${{BOT_TOKEN}},BOT_HOOK_PATH=${{BOT_HOOK_PATH}},YANDEX_HOOK_URL=${{YANDEX_HOOK_URL}}
        source: '.'
        exclude: '.git'
        execution_timeout: 30
