name: Push and Deploy Serverless function
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Install pdf store function
        uses: yc-actions/yc-sls-function@v4.1.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
#          yc-sa-id: $${ secrets.YC_SERVICE_ACCOUNT_ID }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          function-name: ${{ secrets.YC_STORE_LAMBDA_ID }}
          runtime: 'nodejs22'
          entrypoint: 'index.storeHandler'
          environment: |
            YC_REGION=${{ secrets.YC_REGION }}
            YC_S3_ACCESS_KEY=${{ secrets.YC_S3_ACCESS_KEY }}
            YC_S3_SECRET_ACCESS_KEY=${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
            YC_S3_BUCKET=${{ secrets.YC_S3_BUCKET }}
            REQUEST_TIMEOUT=${{ secrets.REQUEST_TIMEOUT }}
          memory: '128Mb'
          include: |
            ./src
            index.js
            package.json
            package-lock.json
          async: true
          async-retries-count: 3
      - name: Install bot function
        uses: yc-actions/yc-sls-function@v4.1.0
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          # yc-sa-id: $${ secrets.YC_SERVICE_ACCOUNT_ID }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          function-name: ${{ secrets.YC_LAMBDA_ID }}
          runtime: 'nodejs22'
          entrypoint: 'index.handler'
          memory: '128Mb'
          execution-timeout: 10
          include: |
            ./src
            index.js
            package.json
            package-lock.json
          environment: |
            LOGIN=${{ secrets.LOGIN }}
            PASSWORD=${{ secrets.PASSWORD }}
            MOSENERGO_LOGIN=${{ secrets.MOSENERGO_LOGIN }}
            MOSENERGO_PASSWORD=${{ secrets.MOSENERGO_PASSWORD }}
            MOSENERGO_ACCOUNT=${{ secrets.MOSENERGO_ACCOUNT }}
            MOSENERGO_ID_KNG=${{ secrets.MOSENERGO_ID_KNG}}
            MOSENERGO_NM_ABN=${{secrets.MOSENERGO_NM_ABN}}
            BOT_TOKEN=${{secrets.BOT_TOKEN}}
            BOT_HOOK_PATH=${{secrets.BOT_HOOK_PATH}}
            YANDEX_HOOK_URL=${{secrets.YANDEX_HOOK_URL}}
            YC_SERVICE_ACCOUNT_ID=${{secrets.YC_SERVICE_ACCOUNT_ID}}
            YC_REGION=${{ secrets.YC_REGION }}
            YC_S3_ACCESS_KEY=${{ secrets.YC_S3_ACCESS_KEY }}
            YC_S3_SECRET_ACCESS_KEY=${{ secrets.YC_S3_SECRET_ACCESS_KEY }}
            YC_S3_BUCKET=${{ secrets.YC_S3_BUCKET }}
            REQUEST_TIMEOUT=${{ secrets.REQUEST_TIMEOUT }}
