name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.YC_TOKEN }}
        function_id: ${{ secrets.YC_LAMBDA_ID }}
        runtime: 'nodejs16'
        memory: '128'
        entrypoint: 'index.handler'
        environment: LOGIN=9990000083,PASSWORD=Neh6zN@aLe,MOSENERGO_LOGIN=vianomore@gmail.com,MOSENERGO_PASSWORD=Mr7RSxPS2mi7dcCV,MOSENERGO_ACCOUNT=2361244,MOSENERGO_ID_KNG=147616,MOSENERGO_NM_ABN=173,BOT_TOKEN=5254661965:AAHXJYHgHbavZzc2OskkUsUdhTyZmV63xJs,BOT_HOOK_PATH=/how-much,YANDEX_HOOK_URL=https://d5dvbvaselvn2d30mv6v.apigw.yandexcloud.net/how-much&drop_pending_updates=true
        source: './release.zip'
        execution_timeout: 30
